language: ruby
rvm:
- 2.3.1
before_install:
- cp spec/support/config/config.sit.yml spec/support/config/config.yml
notifications:
  email:
    on_success: always
    on_failure: always
sudo: false
cache: bundler
deploy:
  script: echo "正在部署到 rubygems.org"
  provider: rubygems
  skip_cleanup: true
  gem:
    lanmao
  on:
    tags: true
  api_key:
    secure: ddd
